apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingCart
  labels:
    app: shoppingCart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingCart
  template:
    metadata:
      labels:
        app: shoppingCart
    spec:
      containers:
        - name: shoppingCart
          image: timagx/nodeapp:v1
          ports:
            - containerPort: 8080

